### ISSUE TITLE
Error connecting to RPC server localhost

### ISSUE THREAD

**Issue by TheKurtix** [karlsen-network/karlsend#13]
Issues karlsenwallet.exe start-daemon

2023-12-07 20:35:43.757 [INF] KSWD: Listening to TCP on localhost:8082
2023-12-07 20:35:43.757 [INF] KSWD: Connecting to a node at localhost...
Error connecting to RPC server localhost: error connecting to address localhost:42110: error connecting to localhost:42110: context deadline exceeded

**Comment by TheKurtix** [comment]
It's OK after run karlsend.exe --utxoindex

**Comment by lemois-1337** [comment]
@TheKurtix Is your problem solved as I would like to close this issue then. This looks more like a support question rather than a bug. :)

**Comment by codepheonix** [comment]
I am having the same problem mine is 
![Uploading 17028514196412021238468038048565.jpg…]()

**Comment by codepheonix** [comment]
Mine is showing KASD: Shutdown complete

**Comment by gabrieldan69** [comment]
same problem here....not fixed with   karlsend.exe --utxoindex

**Comment by deocP** [comment]
Make a backup of Your wallet folder (for saferty) 
default is "C:\Users\*******\AppData\Local\Karlsend" it should be for now ~8GB
and run karlsend.exe /utxoindex - in my case I have to run it twice. 
Wallet will be rebuild (it takes some time to DL and sync 8GB)

**Comment by lemois-1337** [comment]
Original issue is fixed.
