### ISSUE TITLE
How heavy does it weight?

### ISSUE THREAD

**Issue by BarbzYHOOL** [karlsen-network/karlsend#17]
Hello, I have a small SSD, so I wonder how much Gigabytes it will require to mine (first time miner, great opportunity to try)

@lemois-1337 
Thanks

**Comment by lemois-1337** [comment]
You have many miner options, they work all great even on low mem GPU cards currently as we use blake3 algorithm until we switch to another one this year. Regarding the node daemon, it requires in average ~3GB as node is pruning the data and store only from the last 3 days.
