### ISSUE TITLE
Error listening to TCP on localhost:8082:

### ISSUE THREAD

**Issue by gabrieldan69** [karlsen-network/karlsend#25]
wallet cannot start !!

**Comment by Floodcap** [comment]
I am getting the same issue.  I have a fresh download of V1.1.0 and the node has synced.  I just can't get the wallet daemon to start.

**Comment by Floodcap** [comment]
I found a workaround.  Just delete the "Karlsenwallet" application in your "Karlsen" folder and replace it with the "Karlsenwallet" application from V1.0.0.

**Comment by lemois-1337** [comment]
Oh I've overseen this report and created #26 on my own. :) You probably run another wallet like Kaspa as we haven't changed the default port yet. It will be fixed with `v1.2.0` planned for end of January.

**Comment by Floodcap** [comment]
You are correct I've been running a Pyrin node as well.

**Comment by tjayz** [comment]
I had same issue, the problem is the file that is available to dl, the exe anyways, is corrupt. Build from source and no issue. Or I suppose as mentioned above, download v1.0.
