### ISSUE TITLE
Can not get wallet balance

### ISSUE THREAD

**Issue by robermf** [karlsen-network/karlsend#3]
Hello.
I am running the node since yesterday, daemon is also running and shows "Wallet is synced, ready for queries" but when I run the command for get the balance I get: "Total balance,  KLS"

Anyone know how to fix this?

Thanks in advance.

**Comment by Bitcoin-88** [comment]
Yes habe the Same Problem....--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 01.12.23, 16:43 schrieb SpindlerJ ***@***.***>:

   
  I'm having the same problem. On github, when you download the wallet, it says there's a requirement to have Go installed. I'm going to try this, but I doubt, that this will fix the issue. I've also noticed, that the node doesn't give you a message whether it is synced or not.

**Comment by silaslyma** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/105316332/288081975-f9f04ef7-5ba1-43b7-ac32-0386834d6604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODk1NTgsIm5iZiI6MTcwMTc4OTI1OCwicGF0aCI6Ii8xMDUzMTYzMzIvMjg4MDgxOTc1LWY5ZjA0ZWY3LTViYTEtNDNiNy1hYzMyLTAzODY4MzRkNjYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNTE0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Mzk2OWU4MDc4ZjQ0Nzg3N2YyZmU0ZGQxMWVlYmFlNTIzYWNkYjA1OGUwZjJhZDdjMzM5ZDMyYWQwOTEwZjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qFtxuAiUd-VgFVrFtTFQawOXAMRG-WDELARcANCoXPU)
> 
> same problem here, don't show balance, i've been trying since yesterday
> 
> ![sync](https://private-user-images.githubusercontent.com/105316332/288083897-2e268d16-0823-496a-b17f-946f5d61db81.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODk1NTgsIm5iZiI6MTcwMTc4OTI1OCwicGF0aCI6Ii8xMDUzMTYzMzIvMjg4MDgzODk3LTJlMjY4ZDE2LTA4MjMtNDk2YS1iMTdmLTk0NmY1ZDYxZGI4MS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNTE0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTY3ZTQxZDJmYjRmMDRjYTE3NDllNjQwMjU2MDBhMjNlZjdiMWEwZGFjNWM0MmY2YzRiZjc2NzQ3NTRhYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lM8hfXHqSBFVeFwgsBONPh3aklM0XcyX1zSPRGniADQ) and this second one, always syncing, i already closed a few times, but no balance

I already fixed, anyone who has problem, go to discord e download database and replace yours.
[https://discord.gg/tvJKR4T5](url)

**Comment by walterariel1976** [comment]
hello, i have the same problem, balance dont show, i tray to install the datadir2 but i dont know where to put it ,i dont see C:\Users\Username\AppData\Local\   "Karlsend\karlsen-mainnet\datadir2"

**Comment by Chubs21** [comment]
> > ![Untitled](https://private-user-images.githubusercontent.com/105316332/288081975-f9f04ef7-5ba1-43b7-ac32-0386834d6604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODk1NTgsIm5iZiI6MTcwMTc4OTI1OCwicGF0aCI6Ii8xMDUzMTYzMzIvMjg4MDgxOTc1LWY5ZjA0ZWY3LTViYTEtNDNiNy1hYzMyLTAzODY4MzRkNjYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNTE0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Mzk2OWU4MDc4ZjQ0Nzg3N2YyZmU0ZGQxMWVlYmFlNTIzYWNkYjA1OGUwZjJhZDdjMzM5ZDMyYWQwOTEwZjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qFtxuAiUd-VgFVrFtTFQawOXAMRG-WDELARcANCoXPU)
> > same problem here, don't show balance, i've been trying since yesterday
> > ![sync](https://private-user-images.githubusercontent.com/105316332/288083897-2e268d16-0823-496a-b17f-946f5d61db81.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODk1NTgsIm5iZiI6MTcwMTc4OTI1OCwicGF0aCI6Ii8xMDUzMTYzMzIvMjg4MDgzODk3LTJlMjY4ZDE2LTA4MjMtNDk2YS1iMTdmLTk0NmY1ZDYxZGI4MS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxNTE0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTY3ZTQxZDJmYjRmMDRjYTE3NDllNjQwMjU2MDBhMjNlZjdiMWEwZGFjNWM0MmY2YzRiZjc2NzQ3NTRhYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lM8hfXHqSBFVeFwgsBONPh3aklM0XcyX1zSPRGniADQ) and this second one, always syncing, i already closed a few times, but no balance
> 
> I already fixed, anyone who has problem, go to discord e download database and replace yours. [https://discord.gg/tvJKR4T5](url)
the link is not showing anything please help

**Comment by Chubs21** [comment]
Can we check our balance WHILE the mining program is running??? OR do we need to shut that down then run all the commands to see the balance?????     someone PLEASE READ AND ANSWER

**Comment by Chubs21** [comment]
PLEASE ELABORATE WHEN DROPPING LINKS ITS NOT HARD TO WRITE A SENTENCE

**Comment by Redonmyhead** [comment]
I unziped the datadir2 into my karlsen folder.  shows datadir2 folder with the karlsen exe and bat files.  do i just leave datadir2 there and run the 3 commands as mentioned above.  I do not see a dir file to be replaced as mentioned above 
![datadir](https://github.com/karlsen-network/karlsend/assets/153258106/3b3c1250-798d-4ff0-b828-a87fa85a2135)

**Comment by lemois-1337** [comment]
This isn't a support chat, please report bugs with some minimal reproduction scenario please. To give an answer to the question about balance.

Wallet Sync != Node Sync, so please check node sync status with RPC call `GetInfo`, response should be something like:
```
{
    "getInfoResponse": {
        "p2pId": "f9d4cf4b697e4c2a2befcd2736270b08",
        "mempoolSize": "1",
        "serverVersion": "1.0.0",
        "isUtxoIndexed": true,
        "isSynced": true,
        "error": null
    }
}
```

If it is not sync, checks the `virtualDaaScore` via RPC call `GetBlockDagInfo`, response should be something like:

```
{
    "getBlockDagInfoResponse": {
        "networkName": "karlsen-mainnet",
        "blockCount": "231154",
        "headerCount": "4133883",
        "tipHashes": [
            "a4bf24cfdfb3b7108af2ae92295f36ffb52d7de97ac8aba78595303a0d3407e1"
        ],
        "difficulty": 269389918711804.88,
        "pastMedianTime": "1702543041181",
        "virtualParentHashes": [
            "a4bf24cfdfb3b7108af2ae92295f36ffb52d7de97ac8aba78595303a0d3407e1"
        ],
        "pruningPointHash": "3a069a08e9b774d24995caecec6de1d33c0fae50869633035f6f63e4e6336a0a",
        "virtualDaaScore": "3353047",
        "error": null
    }
}
```

RPC calls can be run via `./karlsenctl <RPC-command>`.
