### ISSUE TITLE
RPC ports for karlsend and karlsenwallet should be changed, they are identical with KAS

### ISSUE THREAD

**Issue by blackmennewstyle** [karlsen-network/karlsend#6]
Hello beautiful devs,

Could you consider to change the default RPC ports for `karlsend` and `karlsenwallet`, they are currently the same as `kaspad` and `kaspwallet`.

It is possible to change those values for `kaspad` and `karlsend` in their respective config file BUT sadly not the case for `karlsenwallet`, because just like `kaspawallet`, it must be done in the file https://github.com/karlsen-network/karlsend/blob/master/cmd/karlsenwallet/config.go` before compiling.

**Comment by lemois-1337** [comment]
Fixed with PR #18 and PR #23 as we are going to test new mining algorithm in public testnet in Q1/2024
